// Centralized Achievements Configuration
// This file serves as the single source of truth for all achievement definitions

const ACHIEVEMENTS_CONFIG = {
    // Basic achievements (per_game - reset on game reset)
    first_upgrade: {
        id: 'first_upgrade',
        name: 'First Tool',
        description: 'Buy your first mining tool',
        reward: 10,
        category: 'basic',
        type: 'per_game',
    },
    ten_upgrades: {
        id: 'ten_upgrades',
        name: 'Tool Collector',
        description: 'Own 10 mining tools',
        reward: 100,
        category: 'basic',
        type: 'per_game',
    },
    hundred_upgrades: {
        id: 'hundred_upgrades',
        name: 'Tool Master',
        description: 'Own 100 mining tools',
        reward: 1000,
        category: 'basic',
        type: 'per_game',
    },
    thousand_upgrades: {
        id: 'thousand_upgrades',
        name: 'Tool Legend',
        description: 'Own 1,000 mining tools',
        reward: 10000,
        category: 'basic',
        type: 'per_game',
    },

    // Tool Quantity Achievements - Wooden Pickaxe (per_game)
    wooden_10: {
        id: 'wooden_10',
        name: 'Wooden Army',
        description: 'Own 10 wooden pickaxes',
        reward: 50,
        category: 'basic',
        type: 'per_game',
    },
    wooden_20: {
        id: 'wooden_20',
        name: 'Wooden Battalion',
        description: 'Own 20 wooden pickaxes',
        reward: 150,
        category: 'basic',
        type: 'per_game',
    },
    wooden_30: {
        id: 'wooden_30',
        name: 'Wooden Regiment',
        description: 'Own 30 wooden pickaxes',
        reward: 300,
        category: 'basic',
        type: 'per_game',
    },
    wooden_40: {
        id: 'wooden_40',
        name: 'Wooden Division',
        description: 'Own 40 wooden pickaxes',
        reward: 500,
        category: 'basic',
        type: 'per_game',
    },
    wooden_50: {
        id: 'wooden_50',
        name: 'Wooden Corps',
        description: 'Own 50 wooden pickaxes',
        reward: 1000,
        category: 'basic',
        type: 'per_game',
    },
    wooden_100: {
        id: 'wooden_100',
        name: 'Wooden Legion',
        description: 'Own 100 wooden pickaxes',
        reward: 2500,
        category: 'basic',
        type: 'per_game',
    },

    // Tool Quantity Achievements - Stone Pickaxe (per_game)
    stone_10: {
        id: 'stone_10',
        name: 'Stone Army',
        description: 'Own 10 stone pickaxes',
        reward: 100,
        category: 'basic',
        type: 'per_game',
    },
    stone_20: {
        id: 'stone_20',
        name: 'Stone Battalion',
        description: 'Own 20 stone pickaxes',
        reward: 250,
        category: 'basic',
        type: 'per_game',
    },
    stone_30: {
        id: 'stone_30',
        name: 'Stone Regiment',
        description: 'Own 30 stone pickaxes',
        reward: 500,
        category: 'basic',
        type: 'per_game',
    },
    stone_40: {
        id: 'stone_40',
        name: 'Stone Division',
        description: 'Own 40 stone pickaxes',
        reward: 1000,
        category: 'basic',
        type: 'per_game',
    },
    stone_50: {
        id: 'stone_50',
        name: 'Stone Corps',
        description: 'Own 50 stone pickaxes',
        reward: 2000,
        category: 'basic',
        type: 'per_game',
    },
    stone_100: {
        id: 'stone_100',
        name: 'Stone Legion',
        description: 'Own 100 stone pickaxes',
        reward: 5000,
        category: 'basic',
        type: 'per_game',
    },

    // Tool Quantity Achievements - Iron Pickaxe
    iron_10: {
        id: 'iron_10',
        name: 'Iron Army',
        description: 'Own 10 iron pickaxes',
        reward: 200,
        category: 'basic',
        type: 'per_game',
    },
    iron_20: {
        id: 'iron_20',
        name: 'Iron Battalion',
        description: 'Own 20 iron pickaxes',
        reward: 500,
        category: 'basic',
        type: 'per_game',
    },
    iron_30: {
        id: 'iron_30',
        name: 'Iron Regiment',
        description: 'Own 30 iron pickaxes',
        reward: 1000,
        category: 'basic',
        type: 'per_game',
    },
    iron_40: {
        id: 'iron_40',
        name: 'Iron Division',
        description: 'Own 40 iron pickaxes',
        reward: 2000,
        category: 'basic',
        type: 'per_game',
    },
    iron_50: {
        id: 'iron_50',
        name: 'Iron Corps',
        description: 'Own 50 iron pickaxes',
        reward: 5000,
        category: 'basic',
        type: 'per_game',
    },
    iron_100: {
        id: 'iron_100',
        name: 'Iron Legion',
        description: 'Own 100 iron pickaxes',
        reward: 15000,
        category: 'basic',
        type: 'per_game',
    },

    // Tool Quantity Achievements - Diamond Pickaxe (per_game)
    diamond_10: {
        id: 'diamond_10',
        name: 'Diamond Army',
        description: 'Own 10 diamond pickaxes',
        reward: 500,
        category: 'basic',
        type: 'per_game',
    },
    diamond_20: {
        id: 'diamond_20',
        name: 'Diamond Battalion',
        description: 'Own 20 diamond pickaxes',
        reward: 1250,
        category: 'basic',
        type: 'per_game',
    },
    diamond_30: {
        id: 'diamond_30',
        name: 'Diamond Regiment',
        description: 'Own 30 diamond pickaxes',
        reward: 2500,
        category: 'basic',
        type: 'per_game',
    },
    diamond_40: {
        id: 'diamond_40',
        name: 'Diamond Division',
        description: 'Own 40 diamond pickaxes',
        reward: 5000,
        category: 'basic',
        type: 'per_game',
    },
    diamond_50: {
        id: 'diamond_50',
        name: 'Diamond Corps',
        description: 'Own 50 diamond pickaxes',
        reward: 10000,
        category: 'basic',
        type: 'per_game',
    },
    diamond_100: {
        id: 'diamond_100',
        name: 'Diamond Legion',
        description: 'Own 100 diamond pickaxes',
        reward: 25000,
        category: 'basic',
        type: 'per_game',
    },

    // Tool Quantity Achievements - Netherite Pickaxe (per_game)
    netherite_10: {
        id: 'netherite_10',
        name: 'Netherite Army',
        description: 'Own 10 netherite pickaxes',
        reward: 50000,
        category: 'basic',
        type: 'per_game',
        type: 'per_game'
    },
    netherite_20: {
        id: 'netherite_20',
        name: 'Netherite Battalion',
        description: 'Own 20 netherite pickaxes',
        reward: 125000,
        category: 'basic',
        type: 'per_game',
        type: 'per_game'
    },
    netherite_30: {
        id: 'netherite_30',
        name: 'Netherite Regiment',
        description: 'Own 30 netherite pickaxes',
        reward: 250000,
        category: 'basic',
        type: 'per_game',
        type: 'per_game'
    },
    netherite_40: {
        id: 'netherite_40',
        name: 'Netherite Division',
        description: 'Own 40 netherite pickaxes',
        reward: 500000,
        category: 'basic',
        type: 'per_game',
        type: 'per_game'
    },
    netherite_50: {
        id: 'netherite_50',
        name: 'Netherite Corps',
        description: 'Own 50 netherite pickaxes',
        reward: 1000000,
        category: 'basic',
        type: 'per_game',
        type: 'per_game'
    },
    netherite_100: {
        id: 'netherite_100',
        name: 'Netherite Legion',
        description: 'Own 100 netherite pickaxes',
        reward: 2500000,
        category: 'basic',
        type: 'per_game',
        type: 'per_game'
    },

    // Tool Quantity Achievements - Mining Robot (per_game)
    robot_10: {
        id: 'robot_10',
        name: 'Robot Army',
        description: 'Own 10 mining robots',
        reward: 100000,
        category: 'basic',
        type: 'per_game',
        type: 'per_game'
    },
    robot_20: {
        id: 'robot_20',
        name: 'Robot Battalion',
        description: 'Own 20 mining robots',
        reward: 250000,
        category: 'basic',
        type: 'per_game',
        type: 'per_game',
    },
    robot_30: {
        id: 'robot_30',
        name: 'Robot Regiment',
        description: 'Own 30 mining robots',
        reward: 500000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    robot_40: {
        id: 'robot_40',
        name: 'Robot Division',
        description: 'Own 40 mining robots',
        reward: 1000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    robot_50: {
        id: 'robot_50',
        name: 'Robot Corps',
        description: 'Own 50 mining robots',
        reward: 2000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    robot_100: {
        id: 'robot_100',
        name: 'Robot Legion',
        description: 'Own 100 mining robots',
        reward: 5000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },

    // Tool Quantity Achievements - Automated Mine
    mine_10: {
        id: 'mine_10',
        name: 'Mine Army',
        description: 'Own 10 automated mines',
        reward: 250000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    mine_20: {
        id: 'mine_20',
        name: 'Mine Battalion',
        description: 'Own 20 automated mines',
        reward: 625000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    mine_30: {
        id: 'mine_30',
        name: 'Mine Regiment',
        description: 'Own 30 automated mines',
        reward: 1250000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    mine_40: {
        id: 'mine_40',
        name: 'Mine Division',
        description: 'Own 40 automated mines',
        reward: 2500000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    mine_50: {
        id: 'mine_50',
        name: 'Mine Corps',
        description: 'Own 50 automated mines',
        reward: 5000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    mine_100: {
        id: 'mine_100',
        name: 'Mine Legion',
        description: 'Own 100 automated mines',
        reward: 12500000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },

    // Tool Quantity Achievements - Quantum Miner
    quantum_10: {
        id: 'quantum_10',
        name: 'Quantum Army',
        description: 'Own 10 quantum miners',
        reward: 500000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    quantum_20: {
        id: 'quantum_20',
        name: 'Quantum Battalion',
        description: 'Own 20 quantum miners',
        reward: 1250000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    quantum_30: {
        id: 'quantum_30',
        name: 'Quantum Regiment',
        description: 'Own 30 quantum miners',
        reward: 2500000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    quantum_40: {
        id: 'quantum_40',
        name: 'Quantum Division',
        description: 'Own 40 quantum miners',
        reward: 5000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    quantum_50: {
        id: 'quantum_50',
        name: 'Quantum Corps',
        description: 'Own 50 quantum miners',
        reward: 10000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    quantum_100: {
        id: 'quantum_100',
        name: 'Quantum Legion',
        description: 'Own 100 quantum miners',
        reward: 25000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },

    // Tool Quantity Achievements - Pickaxe Army
    army_10: {
        id: 'army_10',
        name: 'Army of Armies',
        description: 'Own 10 pickaxe armies',
        reward: 1000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    army_20: {
        id: 'army_20',
        name: 'Army Battalion',
        description: 'Own 20 pickaxe armies',
        reward: 2500000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    army_30: {
        id: 'army_30',
        name: 'Army Regiment',
        description: 'Own 30 pickaxe armies',
        reward: 5000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    army_40: {
        id: 'army_40',
        name: 'Army Division',
        description: 'Own 40 pickaxe armies',
        reward: 10000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    army_50: {
        id: 'army_50',
        name: 'Army Corps',
        description: 'Own 50 pickaxe armies',
        reward: 20000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    army_100: {
        id: 'army_100',
        name: 'Army Legion',
        description: 'Own 100 pickaxe armies',
        reward: 50000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },

    // Tool Quantity Achievements - Diamond Legion
    diamond_legion_10: {
        id: 'diamond_legion_10',
        name: 'Diamond Legion Army',
        description: 'Own 10 diamond legions',
        reward: 2500000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    diamond_legion_20: {
        id: 'diamond_legion_20',
        name: 'Diamond Legion Battalion',
        description: 'Own 20 diamond legions',
        reward: 6250000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    diamond_legion_30: {
        id: 'diamond_legion_30',
        name: 'Diamond Legion Regiment',
        description: 'Own 30 diamond legions',
        reward: 12500000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    diamond_legion_40: {
        id: 'diamond_legion_40',
        name: 'Diamond Legion Division',
        description: 'Own 40 diamond legions',
        reward: 25000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    diamond_legion_50: {
        id: 'diamond_legion_50',
        name: 'Diamond Legion Corps',
        description: 'Own 50 diamond legions',
        reward: 50000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    diamond_legion_100: {
        id: 'diamond_legion_100',
        name: 'Diamond Legion Legion',
        description: 'Own 100 diamond legions',
        reward: 125000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },

    // Tool Quantity Achievements - Netherite Swarm
    netherite_swarm_10: {
        id: 'netherite_swarm_10',
        name: 'Netherite Swarm Army',
        description: 'Own 10 netherite swarms',
        reward: 5000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    netherite_swarm_20: {
        id: 'netherite_swarm_20',
        name: 'Netherite Swarm Battalion',
        description: 'Own 20 netherite swarms',
        reward: 12500000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    netherite_swarm_30: {
        id: 'netherite_swarm_30',
        name: 'Netherite Swarm Regiment',
        description: 'Own 30 netherite swarms',
        reward: 25000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    netherite_swarm_40: {
        id: 'netherite_swarm_40',
        name: 'Netherite Swarm Division',
        description: 'Own 40 netherite swarms',
        reward: 50000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    netherite_swarm_50: {
        id: 'netherite_swarm_50',
        name: 'Netherite Swarm Corps',
        description: 'Own 50 netherite swarms',
        reward: 100000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    netherite_swarm_100: {
        id: 'netherite_swarm_100',
        name: 'Netherite Swarm Legion',
        description: 'Own 100 netherite swarms',
        reward: 250000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },

    // Tool Quantity Achievements - Robot Legion
    robot_legion_10: {
        id: 'robot_legion_10',
        name: 'Robot Legion Army',
        description: 'Own 10 robot legions',
        reward: 10000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    robot_legion_20: {
        id: 'robot_legion_20',
        name: 'Robot Legion Battalion',
        description: 'Own 20 robot legions',
        reward: 25000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    robot_legion_30: {
        id: 'robot_legion_30',
        name: 'Robot Legion Regiment',
        description: 'Own 30 robot legions',
        reward: 50000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    robot_legion_40: {
        id: 'robot_legion_40',
        name: 'Robot Legion Division',
        description: 'Own 40 robot legions',
        reward: 100000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    robot_legion_50: {
        id: 'robot_legion_50',
        name: 'Robot Legion Corps',
        description: 'Own 50 robot legions',
        reward: 200000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },
    robot_legion_100: {
        id: 'robot_legion_100',
        name: 'Robot Legion Legion',
        description: 'Own 100 robot legions',
        reward: 500000000,
        category: 'tool_quantity',
        type: 'per_game',
        type: 'per_game',
    },

    // Challenge achievements
    bare_hands: {
        id: 'bare_hands',
        name: 'Bare Hands',
        description: 'Reach 1,000 blocks without using any tools',
        reward: 5000,
        category: 'challenge',
        type: 'per_game',
        type: 'per_game',
    },
    wooden_only: {
        id: 'wooden_only',
        name: 'Wooden Warrior',
        description: 'Reach 10,000 blocks using only wooden pickaxes',
        reward: 25000,
        category: 'challenge',
        type: 'per_game',
        type: 'per_game',
    },
    stone_only: {
        id: 'stone_only',
        name: 'Stone Specialist',
        description: 'Reach 50,000 blocks using only stone pickaxes',
        reward: 100000,
        category: 'challenge',
        type: 'per_game',
        type: 'per_game',
    },
    iron_only: {
        id: 'iron_only',
        name: 'Iron Icon',
        description: 'Reach 250,000 blocks using only iron pickaxes',
        reward: 500000,
        category: 'challenge',
        type: 'per_game',
        type: 'per_game',
    },
    diamond_only: {
        id: 'diamond_only',
        name: 'Diamond Devotee',
        description: 'Reach 1,000,000 blocks using only diamond pickaxes',
        reward: 2500000,
        category: 'challenge',
        type: 'per_game',
        type: 'per_game',
    },
    netherite_only: {
        id: 'netherite_only',
        name: 'Netherite Noble',
        description: 'Reach 5,000,000 blocks using only netherite pickaxes',
        reward: 10000000,
        category: 'challenge',
        type: 'per_game',
        type: 'per_game',
    },

    // Conflicting Achievements (mutually exclusive)
    bare_hands_master: {
        id: 'bare_hands_master',
        name: 'Bare Hands Master',
        description: 'Reach 10,000 blocks without using any tools',
        reward: 50000,
        category: 'basic',
        type: 'per_game',
        type: 'per_game',
        conflicts: ['wooden_only_master', 'stone_only_master', 'iron_only_master', 'diamond_only_master', 'netherite_only_master']
    },
    wooden_only_master: {
        id: 'wooden_only_master',
        name: 'Wooden Only Master',
        description: 'Reach 100,000 blocks using only bare hands and wooden pickaxes',
        reward: 100000,
        category: 'basic',
        type: 'per_game',
        type: 'per_game',
        conflicts: ['bare_hands_master', 'stone_only_master', 'iron_only_master', 'diamond_only_master', 'netherite_only_master']
    },
    stone_only_master: {
        id: 'stone_only_master',
        name: 'Stone Only Master',
        description: 'Reach 500,000 blocks using only bare hands and stone pickaxes',
        reward: 500000,
        category: 'basic',
        type: 'per_game',
        type: 'per_game',
        conflicts: ['bare_hands_master', 'wooden_only_master', 'iron_only_master', 'diamond_only_master', 'netherite_only_master']
    },

    // Click achievements
    click_master: {
        id: 'click_master',
        name: 'Click Master',
        description: 'Click 1,000 times',
        reward: 1000,
        category: 'click',
        type: 'per_game',
        type: 'per_game',
    },
    click_legend: {
        id: 'click_legend',
        name: 'Click Legend',
        description: 'Click 10,000 times',
        reward: 10000,
        category: 'click',
        type: 'per_game',
        type: 'per_game',
    },
    click_god: {
        id: 'click_god',
        name: 'Click God',
        description: 'Click 100,000 times',
        reward: 100000,
        category: 'click',
        type: 'per_game',
        type: 'per_game',
    },
    click_insanity: {
        id: 'click_insanity',
        name: 'Click Insanity',
        description: 'Click 1,000,000 times',
        reward: 1000000,
        category: 'click',
        type: 'per_game',
        type: 'per_game',
    },

    // Efficiency achievements
    efficient_miner: {
        id: 'efficient_miner',
        name: 'Efficient Miner',
        description: 'Generate 100 blocks per click',
        reward: 50000,
        category: 'efficiency',
        type: 'per_game',
        type: 'per_game',
    },
    super_efficient: {
        id: 'super_efficient',
        name: 'Super Efficient',
        description: 'Generate 500 blocks per click',
        reward: 250000,
        category: 'efficiency',
        type: 'per_game',
        type: 'per_game',
    },
    ultra_efficient: {
        id: 'ultra_efficient',
        name: 'Ultra Efficient',
        description: 'Generate 1,000 blocks per click',
        reward: 1000000,
        category: 'efficiency',
        type: 'per_game',
        type: 'per_game',
    },

    // Speed achievements
    speed_demon: {
        id: 'speed_demon',
        name: 'Speed Demon',
        description: 'Generate 10,000 blocks per second',
        reward: 50000,
        category: 'speed',
        type: 'per_game',
        type: 'per_game',
    },
    speed_legend: {
        id: 'speed_legend',
        name: 'Speed Legend',
        description: 'Generate 100,000 blocks per second',
        reward: 500000,
        category: 'speed',
        type: 'per_game',
        type: 'per_game',
    },
    speed_god: {
        id: 'speed_god',
        name: 'Speed God',
        description: 'Generate 1,000,000 blocks per second',
        reward: 5000000,
        category: 'speed',
        type: 'per_game',
        type: 'per_game',
    },

    // Milestone achievements
    first_million: {
        id: 'first_million',
        name: 'First Million',
        description: 'Reach 1,000,000 blocks',
        reward: 100000,
        category: 'milestone',
        type: 'per_game',
        type: 'per_game',
    },
    first_billion: {
        id: 'first_billion',
        name: 'First Billion',
        description: 'Reach 1,000,000,000 blocks',
        reward: 1000000,
        category: 'milestone',
        type: 'per_game',
        type: 'per_game',
    },
    first_trillion: {
        id: 'first_trillion',
        name: 'First Trillion',
        description: 'Reach 1,000,000,000,000 blocks',
        reward: 10000000,
        category: 'milestone',
        type: 'per_game',
        type: 'per_game',
    },

    // Obscure achievements
    prime_clicker: {
        id: 'prime_clicker',
        name: 'Prime Clicker',
        description: 'Click exactly 2, 3, 5, 7, 11, 13, 17, 19, 23, 29 times',
        reward: 12345,
        category: 'obscure',
        type: 'per_game',
    },
    fibonacci_fan: {
        id: 'fibonacci_fan',
        name: 'Fibonacci Fan',
        description: 'Have exactly 1 wooden pickaxe, 1 stone pickaxe, 2 iron pickaxes, 3 diamond pickaxes, 5 netherite pickaxes, 8 mining robots, 13 automated mines, 21 quantum miners, 34 pickaxe armies, 55 diamond legions, 89 netherite swarms, 144 robot legions',
        reward: 98765,
        category: 'obscure',
        type: 'per_game',
    },
    binary_clicker: {
        id: 'binary_clicker',
        name: 'Binary Clicker',
        description: 'Click exactly 1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024 times',
        reward: 2048,
        category: 'obscure',
        type: 'per_game',
    },
    palindrome_blocks: {
        id: 'palindrome_blocks',
        name: 'Palindrome Blocks',
        description: 'Have exactly 11, 22, 33, 44, 55, 66, 77, 88, 99, 111, 121, 131, 141, 151, 161, 171, 181, 191, 202, 212 blocks',
        reward: 12321,
        category: 'obscure',
        type: 'per_game',
    },
    pi_blocks: {
        id: 'pi_blocks',
        name: 'Pi Blocks',
        description: 'Have exactly 3, 31, 314, 3141, 31415, 314159 blocks',
        reward: 314159,
        category: 'obscure',
        type: 'per_game',
    },
    e_blocks: {
        id: 'e_blocks',
        name: 'E Blocks',
        description: 'Have exactly 2, 27, 271, 2718, 27182, 271828 blocks',
        reward: 271828,
        category: 'obscure',
        type: 'per_game',
    },
    golden_ratio: {
        id: 'golden_ratio',
        name: 'Golden Ratio',
        description: 'Have exactly 1 wooden pickaxe, 1 stone pickaxe, 2 iron pickaxes, 3 diamond pickaxes, 5 netherite pickaxes, 8 mining robots, 13 automated mines, 21 quantum miners, 34 pickaxe armies, 55 diamond legions, 89 netherite swarms, 144 robot legions, 233 diamond armies, 377 netherite armies, 610 robot armies, 987 quantum armies, 1597 pickaxe legions, 2584 diamond swarms, 4181 netherite legions, 6765 robot swarms',
        reward: 10946,
        category: 'obscure',
        type: 'per_game',
    },
    square_clicker: {
        id: 'square_clicker',
        name: 'Square Clicker',
        description: 'Click exactly 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400 times',
        reward: 441,
        category: 'obscure',
        type: 'per_game',
    },
    cube_clicker: {
        id: 'cube_clicker',
        name: 'Cube Clicker',
        description: 'Click exactly 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000 times',
        reward: 1331,
        category: 'obscure',
        type: 'per_game',
    },

    // Time-based achievements
    midnight_miner: {
        id: 'midnight_miner',
        name: 'Midnight Miner',
        description: 'Play at exactly midnight (00:00)',
        reward: 12000,
        category: 'time',
        type: 'per_game',
    },
    noon_miner: {
        id: 'noon_miner',
        name: 'Noon Miner',
        description: 'Play at exactly noon (12:00)',
        reward: 12000,
        category: 'time',
        type: 'per_game',
    },
    friday_13th: {
        id: 'friday_13th',
        name: 'Friday the 13th',
        description: 'Play on Friday the 13th',
        reward: 13000,
        category: 'time',
        type: 'per_game',
    },
    leap_year: {
        id: 'leap_year',
        name: 'Leap Year',
        description: 'Play on February 29th',
        reward: 29000,
        category: 'time',
        type: 'per_game',
    },

    // Easter egg achievements
    konami_code: {
        id: 'konami_code',
        name: 'Konami Code',
        description: 'Enter the Konami code while playing (↑↑↓↓←→←→BA)',
        reward: 1337,
        category: 'basic',
        type: 'per_game',
        type: 'per_game',
        hidden: true
    },
    secret_clicker: {
        id: 'secret_clicker',
        name: 'Secret Clicker',
        description: 'Click exactly 42 times (the answer to life, the universe, and everything)',
        reward: 42000,
        category: 'easter_egg',
        type: 'per_game',
    },
    matrix_fan: {
        id: 'matrix_fan',
        name: 'Matrix Fan',
        description: 'Generate exactly 101 blocks per second (binary for 5, like the Matrix)',
        reward: 10101,
        category: 'easter_egg',
        type: 'per_game',
    },
    leet_hacker: {
        id: 'leet_hacker',
        name: 'Leet Hacker',
        description: 'Generate exactly 1337 blocks per second',
        reward: 133700,
        category: 'easter_egg',
        type: 'per_game',
    },
    boomer: {
        id: 'boomer',
        name: 'Boomer',
        description: 'Click exactly 1969 times (year of the moon landing)',
        reward: 196900,
        category: 'easter_egg',
        type: 'per_game',
    },
    y2k: {
        id: 'y2k',
        name: 'Y2K',
        description: 'Click exactly 2000 times',
        reward: 20000,
        category: 'easter_egg',
        type: 'per_game',
    },
    covid_year: {
        id: 'covid_year',
        name: 'COVID Year',
        description: 'Click exactly 2020 times',
        reward: 20200,
        category: 'easter_egg',
        type: 'per_game',
    },

    // Speed and timing achievements
    speed_clicker: {
        id: 'speed_clicker',
        name: 'Speed Clicker',
        description: 'Click 100 times in under 10 seconds',
        reward: 5000,
        category: 'speed_timing',
        type: 'per_game',
    },
    lightning_clicker: {
        id: 'lightning_clicker',
        name: 'Lightning Clicker',
        description: 'Click 500 times in under 30 seconds',
        reward: 25000,
        category: 'speed_timing',
        type: 'per_game',
    },
    rapid_fire: {
        id: 'rapid_fire',
        name: 'Rapid Fire',
        description: 'Click 1000 times in under 60 seconds',
        reward: 100000,
        category: 'speed_timing',
        type: 'per_game',
    },

    // Efficiency and balance achievements
    perfect_balance: {
        id: 'perfect_balance',
        name: 'Perfect Balance',
        description: 'Have exactly equal blocks per click and blocks per second',
        reward: 50000,
        category: 'efficiency_balance',
        type: 'per_game',
    },
    click_dominant: {
        id: 'click_dominant',
        name: 'Click Dominant',
        description: 'Have 10x more blocks per click than blocks per second',
        reward: 25000,
        category: 'efficiency_balance',
        type: 'per_game',
    },
    passive_dominant: {
        id: 'passive_dominant',
        name: 'Passive Dominant',
        description: 'Have 10x more blocks per second than blocks per click',
        reward: 25000,
        category: 'efficiency_balance',
        type: 'per_game',
    },

    // Specific number achievements
    lucky_seven: {
        id: 'lucky_seven',
        name: 'Lucky Seven',
        description: 'Generate exactly 777 blocks per second',
        reward: 7777,
        category: 'specific_numbers',
        type: 'per_game',
    },
    double_lucky: {
        id: 'double_lucky',
        name: 'Double Lucky',
        description: 'Generate exactly 7777 blocks per second',
        reward: 77777,
        category: 'specific_numbers',
        type: 'per_game',
    },
    triple_lucky: {
        id: 'triple_lucky',
        name: 'Triple Lucky',
        description: 'Generate exactly 77777 blocks per second',
        reward: 777777,
        category: 'specific_numbers',
        type: 'per_game',
    },
    binary_master: {
        id: 'binary_master',
        name: 'Binary Master',
        description: 'Generate exactly 11111111111111111111 blocks per second (20 ones in binary)',
        reward: 1048575,
        category: 'specific_numbers',
        type: 'per_game',
    },
    hex_master: {
        id: 'hex_master',
        name: 'Hex Master',
        description: 'Generate exactly 0xDEADBEEF blocks per second (3735928559)',
        reward: 3735928559,
        category: 'specific_numbers',
        type: 'per_game',
    },

    // Pattern achievements
    repeating_pattern: {
        id: 'repeating_pattern',
        name: 'Repeating Pattern',
        description: 'Generate exactly 123, 1234, 12345, 123456, 1234567, 12345678, or 123456789 blocks per second',
        reward: 123456,
        category: 'patterns',
        type: 'per_game',
    },
    palindrome_clicks: {
        id: 'palindrome_clicks',
        name: 'Palindrome Clicks',
        description: 'Click exactly 11, 22, 33, 44, 55, 66, 77, 88, 99, 111, 121, 131, 141, 151, 161, 171, 181, 191, 202, 212 times',
        reward: 12321,
        category: 'patterns',
        type: 'per_game',
    },
    sequential_blocks: {
        id: 'sequential_blocks',
        name: 'Sequential Blocks',
        description: 'Generate exactly 123, 234, 345, 456, 567, 678, 789, 890, 901, 012 blocks per second',
        reward: 45678,
        category: 'patterns',
        type: 'per_game',
    },

    // Mathematical sequence achievements (Tool-based)
    triangular_numbers: {
        id: 'triangular_numbers',
        name: 'Triangular Numbers',
        description: 'Have exactly 1 wooden pickaxe, 3 stone pickaxes, 6 iron pickaxes, 10 diamond pickaxes, 15 netherite pickaxes, 21 mining robots, 28 automated mines, 36 quantum miners, 45 pickaxe armies, 55 diamond legions, 66 netherite swarms, 78 robot legions',
        reward: 21000,
        category: 'mathematical',
        type: 'per_game',
    },
    square_numbers: {
        id: 'square_numbers',
        name: 'Square Numbers',
        description: 'Have exactly 1 wooden pickaxe, 4 stone pickaxes, 9 iron pickaxes, 16 diamond pickaxes, 25 netherite pickaxes, 36 mining robots, 49 automated mines, 64 quantum miners, 81 pickaxe armies, 100 diamond legions, 121 netherite swarms, 144 robot legions',
        reward: 40000,
        category: 'mathematical',
        type: 'per_game',
    },
    cube_numbers: {
        id: 'cube_numbers',
        name: 'Cube Numbers',
        description: 'Have exactly 1 wooden pickaxe, 8 stone pickaxes, 27 iron pickaxes, 64 diamond pickaxes, 125 netherite pickaxes, 216 mining robots, 343 automated mines, 512 quantum miners, 729 pickaxe armies, 1000 diamond legions',
        reward: 10000,
        category: 'mathematical',
        type: 'per_game',
    },

    // Extended Time-based achievements
    early_bird: {
        id: 'early_bird',
        name: 'Early Bird',
        description: 'Play between 5:00 AM and 7:00 AM',
        reward: 5000,
        category: 'extended_time',
        type: 'per_game',
    },
    night_owl: {
        id: 'night_owl',
        name: 'Night Owl',
        description: 'Play between 11:00 PM and 1:00 AM',
        reward: 5000,
        category: 'extended_time',
        type: 'per_game',
    },
    weekend_warrior: {
        id: 'weekend_warrior',
        name: 'Weekend Warrior',
        description: 'Play on a Saturday or Sunday',
        reward: 10000,
        category: 'extended_time',
        type: 'per_game',
    },
    new_year: {
        id: 'new_year',
        name: 'New Year',
        description: 'Play on January 1st',
        reward: 10000,
        category: 'extended_time',
        type: 'per_game',
    },
    christmas: {
        id: 'christmas',
        name: 'Christmas',
        description: 'Play on December 25th',
        reward: 10000,
        category: 'extended_time',
        type: 'per_game',
    },
    halloween: {
        id: 'halloween',
        name: 'Halloween',
        description: 'Play on October 31st',
        reward: 10000,
        category: 'extended_time',
        type: 'per_game',
    },

    // Browser and system achievements (per_account - permanent, no rewards)
    mobile_player: {
        id: 'mobile_player',
        name: 'Mobile Player',
        description: 'Play on a mobile device',
        reward: 0,
        category: 'basic',
        type: 'per_game',
        type: 'per_account'
    },
    desktop_player: {
        id: 'desktop_player',
        name: 'Desktop Player',
        description: 'Play on a desktop computer',
        reward: 0,
        category: 'basic',
        type: 'per_game',
        type: 'per_account'
    },
    chrome_user: {
        id: 'chrome_user',
        name: 'Chrome User',
        description: 'Play using Google Chrome',
        reward: 0,
        category: 'basic',
        type: 'per_game',
        type: 'per_account'
    },
    firefox_user: {
        id: 'firefox_user',
        name: 'Firefox User',
        description: 'Play using Mozilla Firefox',
        reward: 0,
        category: 'basic',
        type: 'per_game',
        type: 'per_account'
    },
    safari_user: {
        id: 'safari_user',
        name: 'Safari User',
        description: 'Play using Safari',
        reward: 0,
        category: 'basic',
        type: 'per_game',
        type: 'per_account'
    },

    // Game state achievements
    zero_to_hero: {
        id: 'zero_to_hero',
        name: 'Zero to Hero',
        description: 'Start with 0 blocks and reach 1,000,000 blocks',
        reward: 50000,
        category: 'game_state',
        type: 'per_game',
    },
    persistent_player: {
        id: 'persistent_player',
        name: 'Persistent Player',
        description: 'Play for more than 24 hours total',
        reward: 100000,
        category: 'game_state',
        type: 'per_game',
    },
    quick_start: {
        id: 'quick_start',
        name: 'Quick Start',
        description: 'Reach 10,000 blocks in under 5 minutes',
        reward: 25000,
        category: 'game_state',
        type: 'per_game',
    },
    slow_and_steady: {
        id: 'slow_and_steady',
        name: 'Slow and Steady',
        description: 'Play for more than 1 hour before buying your first tool',
        reward: 15000,
        category: 'game_state',
        type: 'per_game',
    },

    // Special challenge achievements
    minimalist: {
        id: 'minimalist',
        name: 'Minimalist',
        description: 'Reach 100,000 blocks with only 5 different tools',
        reward: 75000,
        category: 'special_challenge',
        type: 'per_game',
    },
    tool_hoarder: {
        id: 'tool_hoarder',
        name: 'Tool Hoarder',
        description: 'Own at least 1 of every tool type',
        reward: 100000,
        category: 'special_challenge',
        type: 'per_game',
    },
    click_efficiency: {
        id: 'click_efficiency',
        name: 'Click Efficiency',
        description: 'Generate 1000 blocks per click',
        reward: 200000,
        category: 'special_challenge',
        type: 'per_game',
    },
    passive_efficiency: {
        id: 'passive_efficiency',
        name: 'Passive Efficiency',
        description: 'Generate 1,000,000 blocks per second',
        reward: 500000,
        category: 'special_challenge',
        type: 'per_game',
    },

    // Fun and silly achievements
    round_numbers: {
        id: 'round_numbers',
        name: 'Round Numbers',
        description: 'Generate exactly 100, 1000, 10000, 100000, 1000000, 10000000, 100000000, 1000000000 blocks per second',
        reward: 1000000,
        category: 'fun_silly',
        type: 'per_game',
    },
    all_ones: {
        id: 'all_ones',
        name: 'All Ones',
        description: 'Have exactly 111, 1111, 11111, 111111, 1111111, 11111111, 111111111 blocks',
        reward: 111111,
        category: 'fun_silly',
        type: 'per_game',
    },
    all_twos: {
        id: 'all_twos',
        name: 'All Twos',
        description: 'Have exactly 222, 2222, 22222, 222222, 2222222, 22222222, 222222222 blocks',
        reward: 222222,
        category: 'fun_silly',
        type: 'per_game',
    },
    all_threes: {
        id: 'all_threes',
        name: 'All Threes',
        description: 'Have exactly 333, 3333, 33333, 333333, 3333333, 33333333, 333333333 blocks',
        reward: 333333,
        category: 'fun_silly',
        type: 'per_game',
    },
    all_fours: {
        id: 'all_fours',
        name: 'All Fours',
        description: 'Have exactly 444, 4444, 44444, 444444, 4444444, 44444444, 444444444 blocks',
        reward: 444444,
        category: 'fun_silly',
        type: 'per_game',
    },
    all_fives: {
        id: 'all_fives',
        name: 'All Fives',
        description: 'Have exactly 555, 5555, 55555, 555555, 5555555, 55555555, 555555555 blocks',
        reward: 555555,
        category: 'fun_silly',
        type: 'per_game',
    },
    all_sixes: {
        id: 'all_sixes',
        name: 'All Sixes',
        description: 'Have exactly 666, 6666, 66666, 666666, 6666666, 66666666, 666666666 blocks',
        reward: 666666,
        category: 'fun_silly',
        type: 'per_game',
    },
    all_sevens: {
        id: 'all_sevens',
        name: 'All Sevens',
        description: 'Have exactly 777, 7777, 77777, 777777, 7777777, 77777777, 777777777 blocks',
        reward: 777777,
        category: 'fun_silly',
        type: 'per_game',
    },
    all_eights: {
        id: 'all_eights',
        name: 'All Eights',
        description: 'Have exactly 888, 8888, 88888, 888888, 8888888, 88888888, 888888888 blocks',
        reward: 888888,
        category: 'fun_silly',
        type: 'per_game',
    },
    all_nines: {
        id: 'all_nines',
        name: 'All Nines',
        description: 'Have exactly 999, 9999, 99999, 999999, 9999999, 99999999, 999999999 blocks',
        reward: 999999,
        category: 'fun_silly',
        type: 'per_game',
    },

    // Ultra Creative Achievements
    minecraft_reference: {
        id: 'minecraft_reference',
        name: 'Minecraft Reference',
        description: 'Have exactly 64 blocks (stack size in Minecraft)',
        reward: 6400,
        category: 'minecraft_themed',
        type: 'per_game',
    },
    diamond_blocks: {
        id: 'diamond_blocks',
        name: 'Diamond Blocks',
        description: 'Have exactly 9 diamonds worth of blocks (9 * 64 = 576)',
        reward: 57600,
        category: 'minecraft_themed',
        type: 'per_game',
    },
    nether_portal: {
        id: 'nether_portal',
        name: 'Nether Portal',
        description: 'Have exactly 10 obsidian blocks worth (10 * 64 = 640)',
        reward: 64000,
        category: 'minecraft_themed',
        type: 'per_game',
    },
    ender_pearl: {
        id: 'ender_pearl',
        name: 'Ender Pearl',
        description: 'Have exactly 8 ender pearls worth of blocks (8 * 16 = 128)',
        reward: 12800,
        category: 'minecraft_themed',
        type: 'per_game',
    },

    // Keyboard and Input Achievements
    keyboard_warrior: {
        id: 'keyboard_warrior',
        name: 'Keyboard Warrior',
        description: 'Use keyboard shortcuts while playing (Ctrl+C, Ctrl+V, etc.)',
        reward: 5000,
        category: 'input_methods',
        type: 'per_game',
    },
    mouse_master: {
        id: 'mouse_master',
        name: 'Mouse Master',
        description: 'Click with different mouse buttons (left, right, middle)',
        reward: 3000,
        category: 'input_methods',
        type: 'per_game',
    },
    touch_screen: {
        id: 'touch_screen',
        name: 'Touch Screen',
        description: 'Play using touch input on a touchscreen device',
        reward: 4000,
        category: 'input_methods',
        type: 'per_game',
    },

    // Performance and Technical Achievements
    fps_master: {
        id: 'fps_master',
        name: 'FPS Master',
        description: 'Maintain 60+ FPS while playing for 10 minutes',
        reward: 15000,
        category: 'technical',
        type: 'per_game',
    },
    memory_efficient: {
        id: 'memory_efficient',
        name: 'Memory Efficient',
        description: 'Play for 1 hour without the page using more than 100MB RAM',
        reward: 25000,
        category: 'technical',
        type: 'per_game',
    },
    network_warrior: {
        id: 'network_warrior',
        name: 'Network Warrior',
        description: 'Play while having a slow internet connection (< 1Mbps)',
        reward: 10000,
        category: 'technical',
        type: 'per_game',
    },

    // Social and Multiplayer Achievements
    share_master: {
        id: 'share_master',
        name: 'Share Master',
        description: 'Share your game progress on social media',
        reward: 5000,
        category: 'social',
        type: 'per_game',
    },
    screenshot_artist: {
        id: 'screenshot_artist',
        name: 'Screenshot Artist',
        description: 'Take a screenshot while playing',
        reward: 3000,
        category: 'social',
        type: 'per_game',
    },
    streamer: {
        id: 'streamer',
        name: 'Streamer',
        description: 'Play while screen recording or streaming',
        reward: 10000,
        category: 'social',
        type: 'per_game',
    },

    // Environmental Achievements
    dark_mode: {
        id: 'dark_mode',
        name: 'Dark Mode',
        description: 'Play in a dark room with minimal lighting',
        reward: 5000,
        category: 'environment',
        type: 'per_game',
    },
    outdoor_gamer: {
        id: 'outdoor_gamer',
        name: 'Outdoor Gamer',
        description: 'Play outside or near a window with natural light',
        reward: 3000,
        category: 'environment',
        type: 'per_game',
    },
    coffee_gamer: {
        id: 'coffee_gamer',
        name: 'Coffee Gamer',
        description: 'Play while drinking coffee or tea',
        reward: 2000,
        category: 'environment',
        type: 'per_game',
    },

    // Psychological Achievements
    patience_master: {
        id: 'patience_master',
        name: 'Patience Master',
        description: 'Wait 5 minutes without clicking anything',
        reward: 50000,
        category: 'psychological',
        type: 'per_game',
    },
    focus_master: {
        id: 'focus_master',
        name: 'Focus Master',
        description: 'Play for 30 minutes without switching tabs or windows',
        reward: 30000,
        category: 'psychological',
        type: 'per_game',
    },
    zen_miner: {
        id: 'zen_miner',
        name: 'Zen Miner',
        description: 'Click exactly once every 3 seconds for 10 minutes',
        reward: 75000,
        category: 'psychological',
        type: 'per_game',
    },

    // Seasonal and Event Achievements
    summer_gamer: {
        id: 'summer_gamer',
        name: 'Summer Gamer',
        description: 'Play during summer months (June-August)',
        reward: 5000,
        category: 'seasonal',
        type: 'per_game',
    },
    winter_gamer: {
        id: 'winter_gamer',
        name: 'Winter Gamer',
        description: 'Play during winter months (December-February)',
        reward: 5000,
        category: 'seasonal',
        type: 'per_game',
    },
    holiday_spirit: {
        id: 'holiday_spirit',
        name: 'Holiday Spirit',
        description: 'Play on a major holiday (Christmas, New Year, etc.)',
        reward: 15000,
        category: 'seasonal',
        type: 'per_game',
    },

    // Time-based Precision Achievements
    midnight_strike: {
        id: 'midnight_strike',
        name: 'Midnight Strike',
        description: 'Click exactly at midnight (00:00:00)',
        reward: 50000,
        category: 'time_precision',
        type: 'per_game',
    },
    noon_strike: {
        id: 'noon_strike',
        name: 'Noon Strike',
        description: 'Click exactly at noon (12:00:00)',
        reward: 50000,
        category: 'time_precision',
        type: 'per_game',
    },
    second_precision: {
        id: 'second_precision',
        name: 'Second Precision',
        description: 'Click exactly on the 30th second of any minute',
        reward: 10000,
        category: 'time_precision',
        type: 'per_game',
    },

    // Mathematical Mastery Achievements
    pi_master: {
        id: 'pi_master',
        name: 'Pi Master',
        description: 'Have exactly 3.14159 blocks (314159)',
        reward: 314159,
        category: 'mathematical_mastery',
        type: 'per_game',
    },
    e_master: {
        id: 'e_master',
        name: 'E Master',
        description: 'Have exactly 2.71828 blocks (271828)',
        reward: 271828,
        category: 'mathematical_mastery',
        type: 'per_game',
    },
    golden_ratio: {
        id: 'golden_ratio',
        name: 'Golden Ratio',
        description: 'Have exactly 1.61803 blocks (161803)',
        reward: 161803,
        category: 'mathematical_mastery',
        type: 'per_game',
    },
    fibonacci_sequence: {
        id: 'fibonacci_sequence',
        name: 'Fibonacci Sequence',
        description: 'Have exactly 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144 blocks in sequence',
        reward: 500000,
        category: 'mathematical_mastery',
        type: 'per_game',
    },

    // Gaming Culture References
    speedrun_master: {
        id: 'speedrun_master',
        name: 'Speedrun Master',
        description: 'Reach 1,000,000 blocks in under 10 minutes',
        reward: 1000000,
        category: 'gaming_culture',
        type: 'per_game',
    },
    completionist: {
        id: 'completionist',
        name: 'Completionist',
        description: 'Own at least 10 of every tool type',
        reward: 500000,
        category: 'gaming_culture',
        type: 'per_game',
    },
    min_maxer: {
        id: 'min_maxer',
        name: 'Min-Maxer',
        description: 'Optimize your build for maximum efficiency',
        reward: 200000,
        category: 'gaming_culture',
        type: 'per_game',
    },
    casual_gamer: {
        id: 'casual_gamer',
        name: 'Casual Gamer',
        description: 'Play for exactly 30 minutes and then stop',
        reward: 15000,
        category: 'gaming_culture',
        type: 'per_game',
    },

    // Internet and Meme Culture
    doge_miner: {
        id: 'doge_miner',
        name: 'Doge Miner',
        description: 'Have exactly 1337 blocks (much wow, very leet)',
        reward: 133700,
        category: 'meme_culture',
        type: 'per_game',
    },
    pepe_miner: {
        id: 'pepe_miner',
        name: 'Pepe Miner',
        description: 'Have exactly 420 blocks (rare pepe)',
        reward: 42000,
        category: 'meme_culture',
        type: 'per_game',
    },
    wojak_miner: {
        id: 'wojak_miner',
        name: 'Wojak Miner',
        description: 'Play for 4 hours straight (feels bad man)',
        reward: 100000,
        category: 'meme_culture',
        type: 'per_game',
    },

    // Hidden achievements
    inspector: {
        id: 'inspector',
        name: 'Inspector',
        description: 'Open the browser console while playing',
        reward: 5000,
        category: 'basic',
        type: 'per_game',
        type: 'per_game',
        hidden: true
    },
    copy_paste: {
        id: 'copy_paste',
        name: 'Copy Paste',
        description: 'Use copy and paste while playing',
        reward: 3000,
        category: 'basic',
        type: 'per_game',
        type: 'per_game',
        hidden: true
    },
    tab_switcher: {
        id: 'tab_switcher',
        name: 'Tab Switcher',
        description: 'Switch tabs while playing',
        reward: 2000,
        category: 'basic',
        type: 'per_game',
        type: 'per_game',
        hidden: true
    },
    resize_master: {
        id: 'resize_master',
        name: 'Resize Master',
        description: 'Resize the browser window while playing',
        reward: 3000,
        category: 'basic',
        type: 'per_game',
        type: 'per_game',
        hidden: true
    },

    // Meta achievements
    achievement_hunter: {
        id: 'achievement_hunter',
        name: 'Achievement Hunter',
        description: 'Unlock 50 achievements',
        reward: 100000,
        category: 'meta',
        type: 'per_game',
    },
    achievement_collector: {
        id: 'achievement_collector',
        name: 'Achievement Collector',
        description: 'Unlock 100 achievements',
        reward: 500000,
        category: 'meta',
        type: 'per_game',
    },
    achievement_legend: {
        id: 'achievement_legend',
        name: 'Achievement Legend',
        description: 'Unlock 200 achievements',
        reward: 1000000,
        category: 'meta',
        type: 'per_game',
    },
    achievement_god: {
        id: 'achievement_god',
        name: 'Achievement God',
        description: 'Unlock all possible achievements',
        reward: 5000000,
        category: 'basic',
        type: 'per_game',
        type: 'per_game',
        crossRun: true
    },

    // New Creative Achievements - Gameplay Mechanics
    speed_clicker_master: {
        id: 'speed_clicker_master',
        name: 'Speed Clicker Master',
        description: 'Click 100 times in under 5 seconds',
        reward: 50000,
        category: 'speed_challenge',
        type: 'per_game',
    },
    ultra_speed_clicker: {
        id: 'ultra_speed_clicker',
        name: 'Ultra Speed Clicker',
        description: 'Click 500 times in under 15 seconds',
        reward: 200000,
        category: 'speed_challenge',
        type: 'per_game',
    },
    click_god_speed: {
        id: 'click_god_speed',
        name: 'Click God Speed',
        description: 'Click 1000 times in under 30 seconds',
        reward: 1000000,
        category: 'speed_challenge',
        type: 'per_game',
    },

    // Resource Management Achievements
    frugal_miner: {
        id: 'frugal_miner',
        name: 'Frugal Miner',
        description: 'Reach 100,000 blocks without spending any on upgrades',
        reward: 50000,
        category: 'resource_management',
        type: 'per_game',
    },
    hoarder: {
        id: 'hoarder',
        name: 'Hoarder',
        description: 'Have 1,000,000 blocks without buying any upgrades',
        reward: 200000,
        category: 'resource_management',
        type: 'per_game',
    },
    spendthrift: {
        id: 'spendthrift',
        name: 'Spendthrift',
        description: 'Spend 1,000,000 blocks in a single session',
        reward: 100000,
        category: 'resource_management',
        type: 'per_game',
    },
    big_spender: {
        id: 'big_spender',
        name: 'Big Spender',
        description: 'Spend 100,000,000 blocks in a single session',
        reward: 1000000,
        category: 'resource_management',
        type: 'per_game',
    },

    // Timing and Rhythm Achievements
    rhythm_miner: {
        id: 'rhythm_miner',
        name: 'Rhythm Miner',
        description: 'Click exactly once per second for 60 seconds straight',
        reward: 75000,
        category: 'timing',
        type: 'per_game',
    },
    perfect_timing: {
        id: 'perfect_timing',
        name: 'Perfect Timing',
        description: 'Click exactly 60 times in exactly 60 seconds',
        reward: 100000,
        category: 'timing',
        type: 'per_game',
    },
    slow_and_steady: {
        id: 'slow_and_steady',
        name: 'Slow and Steady',
        description: 'Click exactly once every 2 seconds for 5 minutes',
        reward: 150000,
        category: 'timing',
        type: 'per_game',
    },

    // Mathematical and Pattern Achievements
    fibonacci_master: {
        id: 'fibonacci_master',
        name: 'Fibonacci Master',
        description: 'Have exactly 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144 blocks at different times',
        reward: 250000,
        category: 'mathematical_patterns',
        type: 'per_game',
    },
    prime_clicker: {
        id: 'prime_clicker',
        name: 'Prime Clicker',
        description: 'Click exactly 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47 times',
        reward: 300000,
        category: 'mathematical_patterns',
        type: 'per_game',
    },
    square_master: {
        id: 'square_master',
        name: 'Square Master',
        description: 'Have exactly 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225 blocks',
        reward: 200000,
        category: 'mathematical_patterns',
        type: 'per_game',
    },
    cube_master: {
        id: 'cube_master',
        name: 'Cube Master',
        description: 'Have exactly 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000 blocks',
        reward: 150000,
        category: 'mathematical_patterns',
        type: 'per_game',
    },

    // Special Number Achievements
    lucky_numbers: {
        id: 'lucky_numbers',
        name: 'Lucky Numbers',
        description: 'Generate exactly 777, 7777, 77777, 777777 blocks per second',
        reward: 777777,
        category: 'special_numbers',
        type: 'per_game',
    },
    unlucky_numbers: {
        id: 'unlucky_numbers',
        name: 'Unlucky Numbers',
        description: 'Generate exactly 666, 6666, 66666, 666666 blocks per second',
        reward: 666666,
        category: 'special_numbers',
        type: 'per_game',
    },
    binary_master: {
        id: 'binary_master',
        name: 'Binary Master',
        description: 'Generate exactly 10101010101010101010 blocks per second',
        reward: 1000000,
        category: 'special_numbers',
        type: 'per_game',
    },
    hex_master: {
        id: 'hex_master',
        name: 'Hex Master',
        description: 'Generate exactly 0xDEADBEEF blocks per second (3735928559)',
        reward: 3735928559,
        category: 'specific_numbers',
        type: 'per_game',
    },

    // Easter Egg and Hidden Achievements
    konami_code: {
        id: 'konami_code',
        name: 'Konami Code',
        description: 'Enter the Konami code while playing (↑↑↓↓←→←→BA)',
        reward: 1337,
        category: 'basic',
        type: 'per_game',
        type: 'per_game',
        hidden: true
    },
    secret_clicker: {
        id: 'secret_clicker',
        name: 'Secret Clicker',
        description: 'Click exactly 42 times (the answer to life, the universe, and everything)',
        reward: 42000,
        category: 'easter_egg',
        type: 'per_game',
    },
    matrix_fan: {
        id: 'matrix_fan',
        name: 'Matrix Fan',
        description: 'Generate exactly 101 blocks per second (binary for 5, like the Matrix)',
        reward: 10101,
        category: 'easter_egg',
        type: 'per_game',
    },
    leet_hacker: {
        id: 'leet_hacker',
        name: 'Leet Hacker',
        description: 'Generate exactly 1337 blocks per second',
        reward: 133700,
        category: 'easter_egg',
        type: 'per_game',
    },
    boomer: {
        id: 'boomer',
        name: 'Boomer',
        description: 'Click exactly 1969 times (year of the moon landing)',
        reward: 196900,
        category: 'easter_egg',
        type: 'per_game',
    },
    y2k: {
        id: 'y2k',
        name: 'Y2K',
        description: 'Click exactly 2000 times',
        reward: 20000,
        category: 'easter_egg',
        type: 'per_game',
    },
    covid_year: {
        id: 'covid_year',
        name: 'COVID Year',
        description: 'Click exactly 2020 times',
        reward: 20200,
        category: 'easter_egg',
        type: 'per_game',
    },

    // Browser and system achievements (per_account - permanent, no rewards)
    mobile_player: {
        id: 'mobile_player',
        name: 'Mobile Player',
        description: 'Play on a mobile device',
        reward: 0,
        category: 'basic',
        type: 'per_game',
        type: 'per_account'
    },
    desktop_player: {
        id: 'desktop_player',
        name: 'Desktop Player',
        description: 'Play on a desktop computer',
        reward: 0,
        category: 'basic',
        type: 'per_game',
        type: 'per_account'
    },
    chrome_user: {
        id: 'chrome_user',
        name: 'Chrome User',
        description: 'Play using Google Chrome',
        reward: 0,
        category: 'basic',
        type: 'per_game',
        type: 'per_account'
    },
    firefox_user: {
        id: 'firefox_user',
        name: 'Firefox User',
        description: 'Play using Mozilla Firefox',
        reward: 0,
        category: 'basic',
        type: 'per_game',
        type: 'per_account'
    },
    safari_user: {
        id: 'safari_user',
        name: 'Safari User',
        description: 'Play using Safari',
        reward: 0,
        category: 'basic',
        type: 'per_game',
        type: 'per_account'
    },

    // Game state achievements
    zero_to_hero: {
        id: 'zero_to_hero',
        name: 'Zero to Hero',
        description: 'Start with 0 blocks and reach 1,000,000 blocks',
        reward: 50000,
        category: 'game_state',
        type: 'per_game',
    },
    persistent_player: {
        id: 'persistent_player',
        name: 'Persistent Player',
        description: 'Play for more than 24 hours total',
        reward: 100000,
        category: 'game_state',
        type: 'per_game',
    },
    quick_start: {
        id: 'quick_start',
        name: 'Quick Start',
        description: 'Reach 10,000 blocks in under 5 minutes',
        reward: 25000,
        category: 'game_state',
        type: 'per_game',
    },
    slow_and_steady: {
        id: 'slow_and_steady',
        name: 'Slow and Steady',
        description: 'Play for more than 1 hour before buying your first tool',
        reward: 15000,
        category: 'game_state',
        type: 'per_game',
    },

    // Special challenge achievements
    minimalist: {
        id: 'minimalist',
        name: 'Minimalist',
        description: 'Reach 100,000 blocks with only 5 different tools',
        reward: 75000,
        category: 'special_challenge',
        type: 'per_game',
    },
    tool_hoarder: {
        id: 'tool_hoarder',
        name: 'Tool Hoarder',
        description: 'Own at least 1 of every tool type',
        reward: 100000,
        category: 'special_challenge',
        type: 'per_game',
    },
    click_efficiency: {
        id: 'click_efficiency',
        name: 'Click Efficiency',
        description: 'Generate 1000 blocks per click',
        reward: 200000,
        category: 'special_challenge',
        type: 'per_game',
    },
    passive_efficiency: {
        id: 'passive_efficiency',
        name: 'Passive Efficiency',
        description: 'Generate 1,000,000 blocks per second',
        reward: 500000,
        category: 'special_challenge',
        type: 'per_game',
    },

    // Fun and silly achievements
    round_numbers: {
        id: 'round_numbers',
        name: 'Round Numbers',
        description: 'Generate exactly 100, 1000, 10000, 100000, 1000000, 10000000, 100000000, 1000000000 blocks per second',
        reward: 1000000,
        category: 'fun_silly',
        type: 'per_game',
    },
    all_ones: {
        id: 'all_ones',
        name: 'All Ones',
        description: 'Have exactly 111, 1111, 11111, 111111, 1111111, 11111111, 111111111 blocks',
        reward: 111111,
        category: 'fun_silly',
        type: 'per_game',
    },
    all_twos: {
        id: 'all_twos',
        name: 'All Twos',
        description: 'Have exactly 222, 2222, 22222, 222222, 2222222, 22222222, 222222222 blocks',
        reward: 222222,
        category: 'fun_silly',
        type: 'per_game',
    },
    all_threes: {
        id: 'all_threes',
        name: 'All Threes',
        description: 'Have exactly 333, 3333, 33333, 333333, 3333333, 33333333, 333333333 blocks',
        reward: 333333,
        category: 'fun_silly',
        type: 'per_game',
    },
    all_fours: {
        id: 'all_fours',
        name: 'All Fours',
        description: 'Have exactly 444, 4444, 44444, 444444, 4444444, 44444444, 444444444 blocks',
        reward: 444444,
        category: 'fun_silly',
        type: 'per_game',
    },
    all_fives: {
        id: 'all_fives',
        name: 'All Fives',
        description: 'Have exactly 555, 5555, 55555, 555555, 5555555, 55555555, 555555555 blocks',
        reward: 555555,
        category: 'fun_silly',
        type: 'per_game',
    },
    all_sixes: {
        id: 'all_sixes',
        name: 'All Sixes',
        description: 'Have exactly 666, 6666, 66666, 666666, 6666666, 66666666, 666666666 blocks',
        reward: 666666,
        category: 'fun_silly',
        type: 'per_game',
    },
    all_sevens: {
        id: 'all_sevens',
        name: 'All Sevens',
        description: 'Have exactly 777, 7777, 77777, 777777, 7777777, 77777777, 777777777 blocks',
        reward: 777777,
        category: 'fun_silly',
        type: 'per_game',
    },
    all_eights: {
        id: 'all_eights',
        name: 'All Eights',
        description: 'Have exactly 888, 8888, 88888, 888888, 8888888, 88888888, 888888888 blocks',
        reward: 888888,
        category: 'fun_silly',
        type: 'per_game',
    },
    all_nines: {
        id: 'all_nines',
        name: 'All Nines',
        description: 'Have exactly 999, 9999, 99999, 999999, 9999999, 99999999, 999999999 blocks',
        reward: 999999,
        category: 'fun_silly',
        type: 'per_game',
    },

    // Hidden achievements
    inspector: {
        id: 'inspector',
        name: 'Inspector',
        description: 'Open the browser console while playing',
        reward: 5000,
        category: 'basic',
        type: 'per_game',
        hidden: true
    },
    copy_paste: {
        id: 'copy_paste',
        name: 'Copy Paste',
        description: 'Use copy and paste while playing',
        reward: 3000,
        category: 'basic',
        type: 'per_game',
        hidden: true
    },
    tab_switcher: {
        id: 'tab_switcher',
        name: 'Tab Switcher',
        description: 'Switch tabs while playing',
        reward: 2000,
        category: 'basic',
        type: 'per_game',
        hidden: true
    },
    resize_master: {
        id: 'resize_master',
        name: 'Resize Master',
        description: 'Resize the browser window while playing',
        reward: 3000,
        category: 'basic',
        type: 'per_game',
        hidden: true
    },

    // Meta achievements
    achievement_hunter: {
        id: 'achievement_hunter',
        name: 'Achievement Hunter',
        description: 'Unlock 50 achievements',
        reward: 100000,
        category: 'meta',
        type: 'per_game',
    },
    achievement_collector: {
        id: 'achievement_collector',
        name: 'Achievement Collector',
        description: 'Unlock 100 achievements',
        reward: 500000,
        category: 'meta',
        type: 'per_game',
    },
    achievement_legend: {
        id: 'achievement_legend',
        name: 'Achievement Legend',
        description: 'Unlock 200 achievements',
        reward: 1000000,
        category: 'meta',
        type: 'per_game',
    },
    achievement_god: {
        id: 'achievement_god',
        name: 'Achievement God',
        description: 'Unlock all possible achievements',
        reward: 5000000,
        category: 'basic',
        type: 'per_game',
        crossRun: true
    }
};

// Helper functions for working with achievements
const AchievementsHelper = {
    // Get all achievements as an array
    getAllAchievements() {
        return Object.values(ACHIEVEMENTS_CONFIG);
    },

    // Get achievements by category
    getAchievementsByCategory(category) {
        return Object.values(ACHIEVEMENTS_CONFIG).filter(achievement => achievement.category === category);
    },

    // Get achievement by ID
    getAchievementById(id) {
        return ACHIEVEMENTS_CONFIG[id];
    },

    // Get achievement categories
    getCategories() {
        const categories = new Set();
        Object.values(ACHIEVEMENTS_CONFIG).forEach(achievement => {
            categories.add(achievement.category);
        });
        return Array.from(categories);
    },

    // Get achievements for display (without conditions, for UI purposes)
    getAchievementsForDisplay() {
        return Object.values(ACHIEVEMENTS_CONFIG).map(achievement => ({
            id: achievement.id,
            name: achievement.name,
            description: achievement.description,
            reward: achievement.reward,
            category: achievement.category,
            type: achievement.type,
            hidden: achievement.hidden || false,
            conflicts: achievement.conflicts || [],
            crossRun: achievement.crossRun || false
        }));
    },

    // Get achievements for game logic (with conditions)
    getAchievementsForGame() {
        return Object.values(ACHIEVEMENTS_CONFIG).map(achievement => ({
            id: achievement.id,
            name: achievement.name,
            description: achievement.description,
            reward: achievement.reward,
            category: achievement.category,
            type: achievement.type,
            hidden: achievement.hidden || false,
            conflicts: achievement.conflicts || [],
            crossRun: achievement.crossRun || false,
            impossible: achievement.impossible || false
        }));
    }
};

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { ACHIEVEMENTS_CONFIG, AchievementsHelper };
} 